In [53]:
import torch
import math

In [44]:
def d_p(x, p):
    '''
    Prox-function
    '''
    return 1 / (p + 1) * x**(p + 1)


def hessian_vector_product(f, x, v):
    '''
    Hessian-vector product: D^2(f) @ v
    '''
    grad_f = torch.autograd.grad([f(x)], [x], create_graph=True)[0]
    z = grad_f @ v
    z.backward()
    return x.grad


def BDGM(f, x_tilda_k, delta, L3):
    
    grad_f_x_tilda_k = torch.autograd.grad([f(x_tilda_k)], [x_tilda_k], create_graph=True)[0]
    
    z_0 = x_tilda_k
    tau = 3 * delta / (8 * (2 + math.sqrt(2)) * torch.norm(grad_f))
    
    def D2v(z):
        return hessian_vector_product(f, x_tilda_k, z - x_tilda_k)
    
    def rho_k(z):
        '''
        Scaling function
        '''
        return .5 * D2v(f, x_tilda_k, z - x_tilda_k) @ (z - x_tilda_k) \
               + L3 * d_p(z - x_tilda_k, 4)
    
    def beta_rho_k(z_i, z):
        '''
        Bregman distance
        '''
        grad_rho_k = torch.autograd.grad([rho_k(z)])
        return rho_k(z) - rho_k(z_i) - grad_rho_k @ (z - z_i)
    
    def g_x_tilda_k_tau(z):
        grad_g_p = torch.autograd.grad([f(x_tilda_k + tau * (z - x_tilda_k))], [x], create_graph=True)[0]
        grad_g_n = torch.autograd.grad([f(x_tilda_k - tau * (z - x_tilda_k))], [x], create_graph=True)[0]
        return 1 / tau**2 * (grad_g_p + grad_g_n - 2 * grad_f_x_tilda_k)
    
    def g_phi_k_tau(z):
        return grad_f_x_tilda_k + D2v(z) + g_x_tilda_k_tau(z) + L3 * ((z - x_tilda_k)**2).sum() * (z - x_tilda_k)
    
    i = 0
    z_i = z_0
    while True:
        g_phi_k_tau_z_i = g_phi_k_tau(z_i)
        grad_f_z_i = torch.autograd.grad([f(z_i)], [z_i], create_graph=True)[0]
        if torch.norm(g_phi_k_tau_z_i) < 1 / 6 * torch.norm(grad_f_z_i) - delta:
            break
        else:
            
        i += 1

In [45]:
v = torch.Tensor([1, 1])
v.requires_grad_()

x = torch.Tensor([0.1, 0.1])
x.requires_grad_()

tensor([0.1000, 0.1000], requires_grad=True)

In [46]:
def f(x):
    return 3 * x[0] ** 2 + 4 * x[0] * x[1] + x[1] **2

In [47]:
D2v(f, x, v)

tensor([10.,  6.])

In [49]:
v = torch.Tensor([1, 1])
v.requires_grad_()

x = torch.Tensor([0.1, 0.1])
x.requires_grad_()

f = 3 * x[0] ** 2 + 4 * x[0] * x[1] + x[1] **2

grad_f, = torch.autograd.grad([f], [x], create_graph=True)
z = grad_f @ v
z.backward()
x.grad

tensor([10.,  6.])

In [30]:
f

tensor(0.0800, grad_fn=<AddBackward0>)

In [31]:
grad_f

(tensor([1.0000, 0.6000], grad_fn=<AddBackward0>),)

In [10]:
v

tensor([1., 1.], requires_grad=True)

In [11]:
z

tensor(1.6000, grad_fn=<DotBackward>)

In [52]:
v @ grad_f

tensor(1.6000, grad_fn=<DotBackward>)

In [61]:
import cython
cimport scipy.linalg.cython_lapack as lp

SyntaxError: invalid syntax (<ipython-input-61-8a527372c2e5>, line 2)

In [60]:
lp.ssptrd

AttributeError: module 'scipy.linalg.lapack' has no attribute 'ssptrd'

In [1]:
import alglib as al

ModuleNotFoundError: No module named 'alglib'

In [2]:
!which python

/home/ivb/miniconda3/envs/nlp/bin/python


In [24]:
import xalglib
import numpy as np

In [29]:
a = [
    [-1, -2, 1, 2],
    [-2, 3, 0, -2],
    [1, 0, 2, 1],
    [2, -2, 1, 4]
]
n = 4
isupper = True

In [16]:
a, tau, d, e = xalglib.smatrixtd(a, n, isupper)

In [17]:
a

[[1.9866666666666677, 0.9066666666666658, 0.5000000000000002, 0.5],
 [-2.0, -1.3200000000000007, -1.6666666666666665, -0.5],
 [1.0, 0.0, 3.333333333333334, -3.0],
 [2.0, -2.0, 1.0, 4.0]]

In [18]:
tau

[0.0, 1.5999999999999999, 1.3333333333333333]

In [19]:
d

[1.9866666666666677, -1.3200000000000007, 3.333333333333334, 4.0]

In [20]:
e

[0.9066666666666658, -1.6666666666666665, -3.0]

In [25]:
print([149 / 75, -33 / 25, 10 / 3, 4])
print([68 / 75, -5 / 3, -3])

[1.9866666666666666, -1.32, 3.3333333333333335, 4]
[0.9066666666666666, -1.6666666666666667, -3]


In [21]:
q = xalglib.smatrixtdunpackq(a, n, isupper, tau)

In [22]:
q

[[0.13333333333333303, -0.7333333333333335, -0.6666666666666666, 0.0],
 [-0.33333333333333365, -0.6666666666666666, 0.6666666666666666, 0.0],
 [-0.9333333333333332, 0.13333333333333358, -0.33333333333333326, 0.0],
 [0.0, 0.0, 0.0, 1.0]]

In [23]:
a

[[1.9866666666666677, 0.9066666666666658, 0.5000000000000002, 0.5],
 [-2.0, -1.3200000000000007, -1.6666666666666665, -0.5],
 [1.0, 0.0, 3.333333333333334, -3.0],
 [2.0, -2.0, 1.0, 4.0]]

In [26]:
import torch

In [50]:
A = torch.tensor(a, dtype=torch.float32)
I = torch.eye(4)
k = torch.tensor(1, dtype=torch.float32)
c = torch.ones(4, dtype=torch.float32)

In [51]:
k.requires_grad_()

tensor(1., requires_grad=True)

In [52]:
A

tensor([[-1., -2.,  1.,  2.],
        [-2.,  3.,  0., -2.],
        [ 1.,  0.,  2.,  1.],
        [ 2., -2.,  1.,  4.]])

In [53]:
I

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [54]:
k

tensor(1., requires_grad=True)

In [55]:
c

tensor([1., 1., 1., 1.])

In [56]:
f = c.T @ torch.inverse(A + I * k) @ c

In [57]:
f

tensor(0.3281, grad_fn=<DotBackward>)

In [58]:
f.backward()

In [60]:
k.grad

tensor(-0.8069)